### ISSUE TITLE
won't pair when using Nimble

### ISSUE THREAD

**Issue by Lemin2** [tao-j/alpha-ble#1]
Hi tao-j,

Hello, I am a developer interested in using esp32's ble function to remotely control Sony cameras. I saw your project on github and I admire your work very much.

Recently I have been trying to use esp32 to control my zv-1 camera, but I encountered some difficulties. I wrote some programs using the Nimble-Arduino library, but when esp32 tries to pair with the camera, the program gets stuck at `D NimBLEClient: >> secureConnection()` and then an error occurs `E NimBLEClient: secureConnection: failed rc=13`. I consulted some relevant documents and articles and found that after zv-1 turns on the pairing option in the menu and enters the waiting for pairing state, any service request sent by the ble client connected to zv-1 will cause the camera to pop up a confirmation pairing window, and only after the pairing is completed, the remote control function can be used normally.

I downloaded and tested your program and found that the program using nimble-arduino also failed to work properly, while the program using Bluedroid can pair and control normally. I would like to ask you, have you found a way to use Nimble library and pair normally? If so, could you share your experience and code with me? I really appreciate your help and guidance.

Looking forward to your reply.

Best regards

**Comment by tao-j** [comment]
The nimble lib seems to be unstable while using this codebase. Please see here for a history of my exploration. https://github.com/frank26080115/alpha-fairy/pull/31

My conclusion is to use the factory stack(but consumes more memory), not the nimble. It was tested to be working reliably. However, due to hardware resource limitation, i.e. not enough RAM. It is not possible to implement that with m5stick. Need another 64k RAM iirc.


Let me know how it goes, best of luck.

**Comment by tao-j** [comment]
https://electric.garden/m5stack-2an3w/photos/STICKCPLUSV11-Internal-Photos-M5Stack-2an3wstickcplusv11-ex-1-6.pdf

It seems that M5Stack is going to release a new version of the device, dubbed "m5Stick c plus2". This internal image from FCC (July 11 2023) shows that ESP32-PICO-V3-02 is used, which has 8M flash and 2M PSRAM. So we can use the bluedroid BLE stack instead of the NimBLE. Just let everyone know here all hope is not lost.
